### ISSUE TITLE
Support for Python 2.7?

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-tools-api#6]
Hi @AntoineDao, This is not an issue or bug report but more of a "thinking loud" comment.

I see that we only support Python 3.6 or higher which is technically fine. I'm not sure how I feel about not supporting Python 2.7. Would that be a problem? Where do we need to support both Python 2 and 3 and where can we just go with Python 3?

This project can be a great chance to say bye to Python 2 and learn more about the good parts of Python 3. The question is what does that mean for the whole Ladybug Tools development. The core libraries should still support 2 and 3 mainly because we want people to be able to use them from inside Grasshopper and Dynamo. What are your thoughts?

**Comment by AntoineDao** [comment]
My thinking for the purpose of this repo/project is to do 2 things:
1. Ingest JSON formatted objects into a SQL database
2. Manage/output queries from the SQL database to JSON format

This means that we shouldn't have to use any ladybug bug as a dependency and therefore don't need to comply with their potential requirement for Python 2.7. 

Furthermore, I imagine folk will either run this on a server/container/locally (I think we should actively ban anyone expecting to run this server within grasshopper...). The only case where Python 2.7 could be useful is if it is run locally on someone's laptop and they are uncomfortable running 2 python environments. However I reckon this will be a minority and that they might as well use Docker/learn to upgrade their life to Python 3 as the clock for Python 2 support is ticking.

The part above concerns why Python 2 is not necessary. Now let me tempt you with why we actively WANT Python 3 => asyncio libraries have been upgraded significantly in 3.6-3.7 which will result in better server management/threading whenever we start scaling this repo.

**Comment by mostaphaRoudsari** [comment]
PS: @sariths I know you are on vacation but I thought you might also want to add your inputs.

**Comment by chriswmackey** [comment]
The only thing g that I feel strongly about is that the core libraries be supported in both 2 and 3. For these other cases, I think that it is fine if we only do Python 3, though I would suggest we explain such a decision by noting benefits in speed or extensibility of sticking to just Python 3 (rather than saying we didn't support both versions because we were lazy).

**Comment by AntoineDao** [comment]
Depending on how much explaining you want to do you could also just add that Python 2 support is being dropped in a year's time and that big players are also planning on dropping support by then (Pandas and all Numfocus libraries as seen [here](https://python3statement.org/)) and that most of the libraries in the current repo's stack recommend picking up Python3 for new projects because of support drop.

Maybe an easy one to explain folk is also: anything that runs in Grasshopper will have Python 2 support and the rest not?

**Comment by mostaphaRoudsari** [comment]
> The only thing g that I feel strongly about is that the core libraries be supported in both 2 and 3.

> Maybe an easy one to explain folk is also: anything that runs in Grasshopper will have Python 2 support and the rest not?

👍
